// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToggleQuickInfo
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToggleQuickInfoPackageString = "e144a113-29b4-4495-a051-23b9300e41b3";
        public static Guid guidToggleQuickInfoPackage = new Guid(guidToggleQuickInfoPackageString);

        public const string guidToggleQuickInfoPackageCmdSetString = "81d05947-f76c-4ea1-8939-9b1f5639e3b8";
        public static Guid guidToggleQuickInfoPackageCmdSet = new Guid(guidToggleQuickInfoPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToggleCommandId = 0x0100;
    }
}